In [5]:
import numpy as np
newvalue = np.load('Data/Out/a.cc_markov2.npz')["newvalue"]
print(newvalue)
newx = np.load('Data/Out/a.cc_markov2.npz')["newx"]
print(newx)
isentry = np.load('Data/Out/a.cc_markov2.npz')["isentry"]
print(isentry)

[[0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.33694444 0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [1.0764189  0.1       ]
 [0.66228429 0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [1.437822   0.1       ]
 [0.95835587 0.1       ]
 [0.80431155 0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.22117506 0.1       ]
 [1.5828691  0.1       ]
 [1.07936884 0.1       ]
 [0.91648286 0.1       ]
 [0.85958404 0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.1        0.1       ]
 [0.26784638 0.1       ]


In [8]:
profit = np.load('Data/Out/a.cc_pr3.npz')["profit"]
print(profit)

[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 ...
 [0.36250062 0.36250062 0.36249769]
 [0.36250008 0.36250008 0.36249929]
 [0.36249989 0.36249989 0.36249989]]
