In [ ]:
import numpy as np
newvalue = np.load('Data/Out/a.cc_markov2.npz')["newvalue"]
print(newvalue)
newx = np.load('Data/Out/a.cc_markov2.npz')["newx"]
print(newx)
isentry = np.load('Data/Out/a.cc_markov2.npz')["isentry"]
print(isentry)

In [ ]:
profit = np.load('Data/Out/a.cc_pr3.npz')["profit"]
print(profit)

In [ ]:
import numpy as np
newvalue = np.load('Data/Out/a.cc_markov3.npz')["newvalue"]

In [ ]:
newvalue[:,2]

In [ ]:
etable = np.load('Data/Out/a.cc_table3.npz')["etable"]
dtable = np.load('Data/Out/a.cc_table3.npz')["dtable"]


In [ ]:
dtable


In [ ]:
etable

In [ ]:
multfac = np.load('Data/Out/a.cc_table3.npz')["mulfac"]
multfac

In [ ]:
wgrid = np.meshgrid(*[np.arange(2)] * 3, indexing="ij")
wgrid

In [ ]:
wgrid = np.load('Data/Out/a.cc_table3.npz')["wgrid"]

In [ ]:
wgrid.shape

In [ ]:
wtable = np.load('Data/Out/a.cc_table3.npz')["wtable"]
wtable

In [32]:
import numpy as np
pr = np.load('Data/Out/a.cc_pr3.npz')["profit"]
pr

array([[-0.2       , -0.2       , -0.2       ],
       [-0.2       , -0.2       , -0.2       ],
       [-0.2       , -0.2       , -0.2       ],
       ...,
       [ 0.36250062,  0.36250062,  0.36249769],
       [ 0.36250008,  0.36250008,  0.36249929],
       [ 0.36249989,  0.36249989,  0.36249989]])

In [34]:
import numpy as np
newvalue = np.load('Data/Out/a.cc_markov1.npz')["newvalue"]
newvalue

array([[ 0.1       ],
       [ 0.1       ],
       [ 0.1       ],
       [ 0.1       ],
       [ 3.33365281],
       [ 7.78502961],
       [11.47616952],
       [14.2045174 ],
       [16.20882806],
       [17.71934584],
       [18.89430642],
       [19.83542814],
       [20.60820389],
       [21.25584306],
       [21.80775842],
       [22.28461515],
       [22.70136217],
       [23.06901921],
       [23.39387299],
       [23.68007739]])

In [35]:
newx = np.load('Data/Out/a.cc_markov2.npz')["newx"]
newx

array([[0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [7.30312702e-01, 0.00000000e+00],
       [6.90825235e-01, 0.00000000e+00],
       [7.07034110e-01, 0.00000000e+00],
       [7.16096060e-01, 0.00000000e+00],
       [5.41393971e-01, 5.41360674e-01],
       [8.43992809e-01, 0.00000000e+00],
       [8.43992809e-01, 0.00000000e+00],
       [8.25949928e-01, 0.00000000e+00],
       [8.19312530e-01, 0.00000000e+00],
       [8.59945068e-01, 1.47577756e-01],
       [6.87304555e-01, 6.87280513e-01],
       [7.15107274e-01, 0.00000000e+00],
       [7.15107274e-01, 0.00000000e+00],
       [7.15107274e-01, 0.00000000e+00],
       [7.110258